Update `normalize` and add `noArray`
second-state/opencvmini pull request #11
Opened 2023-09-22 14:33 UTC by Charles-Schleich

Update `normalize` function to match WasmEdge/Opencvmini plugin signature.
Add `noArray` function to match WasmEdge/Opencvmini plugin functions.
Added DataType Enum, and making use of the `noArray` function inside the wrapped Rust `normalize` function

2023-10-03 14:32 UTC, Charles-Schleich commented
Hi @dannypsnl 
Could you review this ?
When you are happy I will squash.

2023-10-03 14:58 UTC, dannypsnl requested changes

2023-10-03 14:58 UTC, dannypsnl commented on src/interpolation.rs
> +}
eof

2023-10-05 09:44 UTC, Charles-Schleich commented on src/interpolation.rs
> +}
@dannypsnl added newline to end of file

2023-10-05 09:44 UTC, dannypsnl approved these changes

2023-10-05 09:46 UTC, merged